### ISSUE TITLE
slow_cooker docker image not on hub

### ISSUE THREAD

**Issue by richardmarshall** [BuoyantIO/slow_cooker#39]
The docker image `buoyantio/slow_cooker` referenced in [marathon/slow_cooker.json](https://github.com/BuoyantIO/slow_cooker/blob/3488354bc3630a1b00db61fd55dc9e434dfe6a0f/marathon/slow_cooker.json#L7) does not exist on the docker hub.

**Comment by siggy** [comment]
@richardmarshall: Thanks for the report!

`buoyantio/slow_cooker` was mistakenly marked as private. We've made it public, let us know if you encounter further issues.
