### ISSUE TITLE
consider automated docker hub build

### ISSUE THREAD

**Issue by siggy** [BuoyantIO/slow_cooker#48]
The [Dockerhub](https://github.com/BuoyantIO/slow_cooker/blob/022f3040668a9a8c18dccc55ab64df7d5004a58e/RELEASE.md#dockerhub) section of our release process could be replaced with an Automated Build on Docker Hub. It works via Docker Hub listening for changes on the Github repo. A change in the `master` branch triggers a new `latest` docker image. A new git tag/release triggers a new tagged docker image.

It also provides some additional context when viewed on Docker Hub, including the `Dockerfile`, note the differences between:
https://hub.docker.com/r/buoyantio/slow_cooker/
https://hub.docker.com/r/buoyantio/linkerd-viz/

A downside to this setup is we can't change an existing Docker Hub repo to be an Automated build. We have to delete it and recreate. There's currently one tagged image, `1.0.1`, which we could manually push once the repo is replaced.

Thoughts? /cc @stevej

**Comment by stevej** [comment]
You're right, the Automated Build page looks much better. I say go for it.
