### ISSUE TITLE
@file for url option?

### ISSUE THREAD

**Issue by bateau84** [BuoyantIO/slow_cooker#50]
Hey!

I was wondering if its possible to use @ to include a file with urls in the url option?
Want to run this on a list of random urls (in the same web application) to loadtest (like -f in siege).

**Comment by klingerf** [comment]
👍  to this idea -- I've also been wanting the ability to specify multiple URLs as targets.

**Comment by richardmarshall** [comment]
Taking a stab at implementing this since we need it for our use case.

**Comment by wmorgan** [comment]
@richardmarshall awesome!

**Comment by wmorgan** [comment]
We did it, everyone! We beat the lawyers!
