### ISSUE TITLE
Document missing option -method

### ISSUE THREAD

**Issue by jcsalem** [BuoyantIO/slow_cooker#53]
I almost didn't use slow_cooker because it looked like it didn't support POST requests.
Looking through the code I saw the -method argument. Would be great to have it documented in the README.md

**Comment by klingerf** [comment]
@jcsalem Thanks for reporting this! I took a stab at improved flag documentation, here:

https://github.com/BuoyantIO/slow_cooker/tree/kl/document-flags#flags
